### ISSUE TITLE
Support for Generating .fly directory from dockerfile-laravel?

### ISSUE THREAD

**Issue by KTanAug21** [fly-apps/dockerfile-laravel#17]
Should the `.fly` directory, which contains the `/scripts` folder that runs commands for caching, etc, be generated from the dockerfile-laravel command?

**No:**
1. The name of the repository is `dockerfile-laravel`, from the name, it is assumed that the command generates dockerfile-related stuff. Not fly scripts 

**Yes:**
1. The dockerfile-laravel is already used by flyctl to generate the Dockerfile, it makes sense for it to generate other supporting scripts as well, like those found in the `.fly` directory
2. Although the .fly scripts are not Dockerfile variations, these scripts contain startup commands the Dockerfile use for deploying a Laravel app to Fly.io. So since these are used by the Dockerfile( to setup a Laravel app for production ), we can say that these scripts are "deploy-to-fly-production" scripts, hence an indirect part of a Dockerfile the generated.

**Comment by rubys** [comment]
I'm definitely in the "yes" camp.  :-)

These files should not only be in `dockerfile-laravel`, they should be blade templates to enable future customization.

Where possible, it would be nice if `dockerfile-laravel` could be used by non fly.io users.  You can test to see if the project is a fly project using:

```php
if (file_exists('fly.toml')) {
```

On initial launch `flyctl` will create an empty `fly.toml` before calling the dockerfile generator.  Even better: the generator can write to the `fly.toml`, and selected portions will be merged into the eventual `fly.toml`:

https://github.com/superfly/flyctl/blob/42667dfeca123234e4e85946df22bd01406cc4f9/internal/command/launch/launch_frameworks.go#L135-L154
