### ISSUE TITLE
Add Entrypoint to Dockerfile to start the application server

### ISSUE THREAD

**Issue by KTanAug21** [fly-apps/dockerfile-laravel#3]
The current [Dockerfile template](https://github.com/fly-apps/dockerfile-laravel/blob/main/resources/views/dockerfile.blade.php) used in the repository ends at EXPOSE 8080. 

I'm not sure yet whether this starts the server or not though, gonna do some testing. After testing, I should be able to identify whether the Dockerfile starts a server or not. If it does not, Run a command that will run the server.

**Comment by fideloper** [comment]
hi! The base image defines the entrypoint, I took it out of the Dockerfile here as I think it was actually redundant  (although definitely confirm that yourself, I could be wrong!)

**Comment by KTanAug21** [comment]
> hi! The base image defines the entrypoint, I took it out of the Dockerfile here as I think it was actually redundant (although definitely confirm that yourself, I could be wrong!)

Hi @fideloper !!!  Oh I see! Yup I can see there's an [ENTRYPOINT in laravel-docker](https://github.com/fly-apps/laravel-docker/blob/f2a8d80f43b3be7988dcf88d948e15342e260dc2/src/Dockerfile#L48), didn't think to look at that file before. Thanks for the save!

**Comment by KTanAug21** [comment]
Closing this as the Dockerfile generated makes use of the laravel-docker repository's published image, which does [declare an ENTRYPOINT](https://github.com/fly-apps/laravel-docker/blob/f2a8d80f43b3be7988dcf88d948e15342e260dc2/src/Dockerfile#L48) for starting the server.

Thanks @fideloper !
